### ISSUE TITLE
Need a license

### ISSUE THREAD

**Issue by NikKovIos** [i05nagai/ios-instagram-like-filter#1]
Hello and thanks for the great lib!
We are developing the insta-like picker https://github.com/Yummypets/YPImagePicker and wanted to take the filters from your repo. Of course we updated the code for our needs, but used your's like a template. 

From "https://choosealicense.com/no-permission/"
"If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose."

So please add a license :)

**Comment by i05nagai** [comment]
Hi, thank you for contacting me about the license issue. This repository is created as one of the tutorials for features of CIFilter. If this helps your coding, that's great 😃 

I usually use the MIT license, so I'll apply MIT license to this repository. I think this doesn't bother you because the repository which you are contributing to has also MIT license.
However, there is no big reason to use the MIT license. Please let me know if you mind. I'll merge the PR after you confirm it.
https://github.com/i05nagai/ios-instagram-like-filter/pull/2

**Comment by NikKovIos** [comment]
Yes, MIT is convenient for our reasons)

**Comment by i05nagai** [comment]
Merged :D
